# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fila.v1 import admin_pb2 as fila_dot_v1_dot_admin__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fila/v1/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FilaAdminStub(object):
    """Admin RPCs for operators and the CLI.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateQueue = channel.unary_unary(
                '/fila.v1.FilaAdmin/CreateQueue',
                request_serializer=fila_dot_v1_dot_admin__pb2.CreateQueueRequest.SerializeToString,
                response_deserializer=fila_dot_v1_dot_admin__pb2.CreateQueueResponse.FromString,
                _registered_method=True)
        self.DeleteQueue = channel.unary_unary(
                '/fila.v1.FilaAdmin/DeleteQueue',
                request_serializer=fila_dot_v1_dot_admin__pb2.DeleteQueueRequest.SerializeToString,
                response_deserializer=fila_dot_v1_dot_admin__pb2.DeleteQueueResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/fila.v1.FilaAdmin/SetConfig',
                request_serializer=fila_dot_v1_dot_admin__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=fila_dot_v1_dot_admin__pb2.SetConfigResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/fila.v1.FilaAdmin/GetConfig',
                request_serializer=fila_dot_v1_dot_admin__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=fila_dot_v1_dot_admin__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.ListConfig = channel.unary_unary(
                '/fila.v1.FilaAdmin/ListConfig',
                request_serializer=fila_dot_v1_dot_admin__pb2.ListConfigRequest.SerializeToString,
                response_deserializer=fila_dot_v1_dot_admin__pb2.ListConfigResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/fila.v1.FilaAdmin/GetStats',
                request_serializer=fila_dot_v1_dot_admin__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=fila_dot_v1_dot_admin__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.Redrive = channel.unary_unary(
                '/fila.v1.FilaAdmin/Redrive',
                request_serializer=fila_dot_v1_dot_admin__pb2.RedriveRequest.SerializeToString,
                response_deserializer=fila_dot_v1_dot_admin__pb2.RedriveResponse.FromString,
                _registered_method=True)
        self.ListQueues = channel.unary_unary(
                '/fila.v1.FilaAdmin/ListQueues',
                request_serializer=fila_dot_v1_dot_admin__pb2.ListQueuesRequest.SerializeToString,
                response_deserializer=fila_dot_v1_dot_admin__pb2.ListQueuesResponse.FromString,
                _registered_method=True)


class FilaAdminServicer(object):
    """Admin RPCs for operators and the CLI.
    """

    def CreateQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Redrive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQueues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilaAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQueue,
                    request_deserializer=fila_dot_v1_dot_admin__pb2.CreateQueueRequest.FromString,
                    response_serializer=fila_dot_v1_dot_admin__pb2.CreateQueueResponse.SerializeToString,
            ),
            'DeleteQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteQueue,
                    request_deserializer=fila_dot_v1_dot_admin__pb2.DeleteQueueRequest.FromString,
                    response_serializer=fila_dot_v1_dot_admin__pb2.DeleteQueueResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=fila_dot_v1_dot_admin__pb2.SetConfigRequest.FromString,
                    response_serializer=fila_dot_v1_dot_admin__pb2.SetConfigResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=fila_dot_v1_dot_admin__pb2.GetConfigRequest.FromString,
                    response_serializer=fila_dot_v1_dot_admin__pb2.GetConfigResponse.SerializeToString,
            ),
            'ListConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConfig,
                    request_deserializer=fila_dot_v1_dot_admin__pb2.ListConfigRequest.FromString,
                    response_serializer=fila_dot_v1_dot_admin__pb2.ListConfigResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=fila_dot_v1_dot_admin__pb2.GetStatsRequest.FromString,
                    response_serializer=fila_dot_v1_dot_admin__pb2.GetStatsResponse.SerializeToString,
            ),
            'Redrive': grpc.unary_unary_rpc_method_handler(
                    servicer.Redrive,
                    request_deserializer=fila_dot_v1_dot_admin__pb2.RedriveRequest.FromString,
                    response_serializer=fila_dot_v1_dot_admin__pb2.RedriveResponse.SerializeToString,
            ),
            'ListQueues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQueues,
                    request_deserializer=fila_dot_v1_dot_admin__pb2.ListQueuesRequest.FromString,
                    response_serializer=fila_dot_v1_dot_admin__pb2.ListQueuesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fila.v1.FilaAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fila.v1.FilaAdmin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FilaAdmin(object):
    """Admin RPCs for operators and the CLI.
    """

    @staticmethod
    def CreateQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fila.v1.FilaAdmin/CreateQueue',
            fila_dot_v1_dot_admin__pb2.CreateQueueRequest.SerializeToString,
            fila_dot_v1_dot_admin__pb2.CreateQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fila.v1.FilaAdmin/DeleteQueue',
            fila_dot_v1_dot_admin__pb2.DeleteQueueRequest.SerializeToString,
            fila_dot_v1_dot_admin__pb2.DeleteQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fila.v1.FilaAdmin/SetConfig',
            fila_dot_v1_dot_admin__pb2.SetConfigRequest.SerializeToString,
            fila_dot_v1_dot_admin__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fila.v1.FilaAdmin/GetConfig',
            fila_dot_v1_dot_admin__pb2.GetConfigRequest.SerializeToString,
            fila_dot_v1_dot_admin__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fila.v1.FilaAdmin/ListConfig',
            fila_dot_v1_dot_admin__pb2.ListConfigRequest.SerializeToString,
            fila_dot_v1_dot_admin__pb2.ListConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fila.v1.FilaAdmin/GetStats',
            fila_dot_v1_dot_admin__pb2.GetStatsRequest.SerializeToString,
            fila_dot_v1_dot_admin__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Redrive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fila.v1.FilaAdmin/Redrive',
            fila_dot_v1_dot_admin__pb2.RedriveRequest.SerializeToString,
            fila_dot_v1_dot_admin__pb2.RedriveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListQueues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fila.v1.FilaAdmin/ListQueues',
            fila_dot_v1_dot_admin__pb2.ListQueuesRequest.SerializeToString,
            fila_dot_v1_dot_admin__pb2.ListQueuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
