# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fila/v1/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fila/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fila.v1 import messages_pb2 as fila_dot_v1_dot_messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66ila/v1/service.proto\x12\x07\x66ila.v1\x1a\x16\x66ila/v1/messages.proto\"\x97\x01\n\x0e\x45nqueueRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x35\n\x07headers\x18\x02 \x03(\x0b\x32$.fila.v1.EnqueueRequest.HeadersEntry\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\x0f\x45nqueueResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\"\x1f\n\x0e\x43onsumeRequest\x12\r\n\x05queue\x18\x01 \x01(\t\"X\n\x0f\x43onsumeResponse\x12!\n\x07message\x18\x01 \x01(\x0b\x32\x10.fila.v1.Message\x12\"\n\x08messages\x18\x02 \x03(\x0b\x32\x10.fila.v1.Message\"/\n\nAckRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\"\r\n\x0b\x41\x63kResponse\"?\n\x0bNackRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x0e\n\x0cNackResponse\"@\n\x13\x42\x61tchEnqueueRequest\x12)\n\x08messages\x18\x01 \x03(\x0b\x32\x17.fila.v1.EnqueueRequest\"D\n\x14\x42\x61tchEnqueueResponse\x12,\n\x07results\x18\x01 \x03(\x0b\x32\x1b.fila.v1.BatchEnqueueResult\"\\\n\x12\x42\x61tchEnqueueResult\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x18.fila.v1.EnqueueResponseH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\x08\n\x06result2\xbf\x02\n\x0b\x46ilaService\x12<\n\x07\x45nqueue\x12\x17.fila.v1.EnqueueRequest\x1a\x18.fila.v1.EnqueueResponse\x12K\n\x0c\x42\x61tchEnqueue\x12\x1c.fila.v1.BatchEnqueueRequest\x1a\x1d.fila.v1.BatchEnqueueResponse\x12>\n\x07\x43onsume\x12\x17.fila.v1.ConsumeRequest\x1a\x18.fila.v1.ConsumeResponse0\x01\x12\x30\n\x03\x41\x63k\x12\x13.fila.v1.AckRequest\x1a\x14.fila.v1.AckResponse\x12\x33\n\x04Nack\x12\x14.fila.v1.NackRequest\x1a\x15.fila.v1.NackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fila.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENQUEUEREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_ENQUEUEREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_ENQUEUEREQUEST']._serialized_start=59
  _globals['_ENQUEUEREQUEST']._serialized_end=210
  _globals['_ENQUEUEREQUEST_HEADERSENTRY']._serialized_start=164
  _globals['_ENQUEUEREQUEST_HEADERSENTRY']._serialized_end=210
  _globals['_ENQUEUERESPONSE']._serialized_start=212
  _globals['_ENQUEUERESPONSE']._serialized_end=249
  _globals['_CONSUMEREQUEST']._serialized_start=251
  _globals['_CONSUMEREQUEST']._serialized_end=282
  _globals['_CONSUMERESPONSE']._serialized_start=284
  _globals['_CONSUMERESPONSE']._serialized_end=372
  _globals['_ACKREQUEST']._serialized_start=374
  _globals['_ACKREQUEST']._serialized_end=421
  _globals['_ACKRESPONSE']._serialized_start=423
  _globals['_ACKRESPONSE']._serialized_end=436
  _globals['_NACKREQUEST']._serialized_start=438
  _globals['_NACKREQUEST']._serialized_end=501
  _globals['_NACKRESPONSE']._serialized_start=503
  _globals['_NACKRESPONSE']._serialized_end=517
  _globals['_BATCHENQUEUEREQUEST']._serialized_start=519
  _globals['_BATCHENQUEUEREQUEST']._serialized_end=583
  _globals['_BATCHENQUEUERESPONSE']._serialized_start=585
  _globals['_BATCHENQUEUERESPONSE']._serialized_end=653
  _globals['_BATCHENQUEUERESULT']._serialized_start=655
  _globals['_BATCHENQUEUERESULT']._serialized_end=747
  _globals['_FILASERVICE']._serialized_start=750
  _globals['_FILASERVICE']._serialized_end=1069
# @@protoc_insertion_point(module_scope)
