# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fila/v1/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fila/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fila.v1 import messages_pb2 as fila_dot_v1_dot_messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66ila/v1/service.proto\x12\x07\x66ila.v1\x1a\x16\x66ila/v1/messages.proto\"\x97\x01\n\x0e\x45nqueueRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x35\n\x07headers\x18\x02 \x03(\x0b\x32$.fila.v1.EnqueueRequest.HeadersEntry\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\x0f\x45nqueueResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\"\x1f\n\x0e\x43onsumeRequest\x12\r\n\x05queue\x18\x01 \x01(\t\"4\n\x0f\x43onsumeResponse\x12!\n\x07message\x18\x01 \x01(\x0b\x32\x10.fila.v1.Message\"/\n\nAckRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\"\r\n\x0b\x41\x63kResponse\"?\n\x0bNackRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x0e\n\x0cNackResponse2\xf2\x01\n\x0b\x46ilaService\x12<\n\x07\x45nqueue\x12\x17.fila.v1.EnqueueRequest\x1a\x18.fila.v1.EnqueueResponse\x12>\n\x07\x43onsume\x12\x17.fila.v1.ConsumeRequest\x1a\x18.fila.v1.ConsumeResponse0\x01\x12\x30\n\x03\x41\x63k\x12\x13.fila.v1.AckRequest\x1a\x14.fila.v1.AckResponse\x12\x33\n\x04Nack\x12\x14.fila.v1.NackRequest\x1a\x15.fila.v1.NackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fila.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENQUEUEREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_ENQUEUEREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_ENQUEUEREQUEST']._serialized_start=59
  _globals['_ENQUEUEREQUEST']._serialized_end=210
  _globals['_ENQUEUEREQUEST_HEADERSENTRY']._serialized_start=164
  _globals['_ENQUEUEREQUEST_HEADERSENTRY']._serialized_end=210
  _globals['_ENQUEUERESPONSE']._serialized_start=212
  _globals['_ENQUEUERESPONSE']._serialized_end=249
  _globals['_CONSUMEREQUEST']._serialized_start=251
  _globals['_CONSUMEREQUEST']._serialized_end=282
  _globals['_CONSUMERESPONSE']._serialized_start=284
  _globals['_CONSUMERESPONSE']._serialized_end=336
  _globals['_ACKREQUEST']._serialized_start=338
  _globals['_ACKREQUEST']._serialized_end=385
  _globals['_ACKRESPONSE']._serialized_start=387
  _globals['_ACKRESPONSE']._serialized_end=400
  _globals['_NACKREQUEST']._serialized_start=402
  _globals['_NACKREQUEST']._serialized_end=465
  _globals['_NACKRESPONSE']._serialized_start=467
  _globals['_NACKRESPONSE']._serialized_end=481
  _globals['_FILASERVICE']._serialized_start=484
  _globals['_FILASERVICE']._serialized_end=726
# @@protoc_insertion_point(module_scope)
